### PR TITLE
5000 mAh battery case

### PR DESCRIPTION
**Pull request by ssttaarr33**
Case design to fit the T-display with a 5000 mAh battery. The original buttons are used.

### CODE REVIEW

**Comment by landonr** [comment]
Looks great! Can you rename the images to something more descriptive? Did you base this off of the other design? We should a bit more description

**Comment by ssttaarr33** [comment]
> Looks great! Can you rename the images to something more descriptive? Did you base this off of the other design? We should a bit more description

I renamed the images.
The only base that i used are the buttons. I designed using them as a base, hence I added them as the original file.
Where should i add the description?

**Comment by landonr** [comment]
You can make a Readme.md file in the directory, then it will show in github. I'll add that for the other cases

**Comment by ssttaarr33** [comment]
> You can make a Readme.md file in the directory, then it will show in github. I'll add that for the other cases

Done

**Comment by landonr** [comment]
Nicely done! I'll print this out this weekend and try it out, I had the same issue with a battery I bought

**Pull request merged**
