### PR TITLE
Support for Lilygo T-Embed device.  WIP

### PR DESCRIPTION
**Pull request by lmatter**
I basically works, but there are still some to-dos:

1. figure out a back button solution (there is only one button)
2. enable display on startup - I have to enable it via HomeAssitant (and power on as well)
3. It also doesn't work until you configure it on HomeAssistant.
4. Better fonts
5. Battery support

### CODE REVIEW

**Comment by landonr** [comment]
I wish I could get this working on a regular tdisplay s3! I tried a bunch of different configs but I can't get the display to work. ill look into getting a tembed!

**Comment by landonr** [comment]
bought a tembed

**Comment by landonr** [comment]
tembed was stolen from the mail

**Comment by landonr** [comment]
[tembed.txt](https://github.com/landonr/homeThing/files/11819911/tembed.txt)
@sbur83 sent me this

**Comment by sbur83** [comment]
Never mind what I was doing with the microphone there, mic on was a last ditch effort to get ADC to work for voice assistant using assist; no luck there but DAC is working for sound. The on boot lambda is what's needed, check the link at the bottom for detailed information on getting this kit working with esphome and overcoming the conflicting pin issue using fastled.
I will try the kit with homething when I get a minute, I'm thinking in the ipod binary sensor file we could add an on multipress function to toggle a binary sensor and id it same as the rotary up pin but I'm just a hack with this stuff and lando will probably know of a more elegant way.

**Comment by landonr** [comment]
this is what im using to do the select hold for detail on simple rotary encoders with a button
```
binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: 12
      inverted: true
      mode:
        input: true
        pullup: true
    id: sw1
    on_click:
      min_length: 5ms
      max_length: 350ms
      then:
      - lambda: |-
          id(homeThingMenu)->buttonPressSelect();
    on_multi_click:
    - timing:
        - ON for at least 0.5s
      then:
      - lambda: |-
          id(homeThingMenu)->buttonPressSelectHold();
```

**Pull request closed without merging**
